package com.fooddelivery.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;

/**
 * JWT Token Provider for parsing and validating JWT tokens.
 * 
 * Responsibilities:
 * - Parse JWT tokens from Authorization header
 * - Validate token signature, expiration, and issuer
 * - Extract claims (userId, email, role) from tokens
 * 
 * Tokens are expected to be generated by API Gateway with the following structure:
 * {
 *   "userId": "customer-123",
 *   "email": "john@example.com",
 *   "role": "CUSTOMER",
 *   "iss": "api-gateway",
 *   "exp": 1234567890
 * }
 */
@Component
@Slf4j
public class JwtTokenProvider {

    private final SecretKey secretKey;
    private final String expectedIssuer;

    public JwtTokenProvider(
            @Value("${security.jwt.secret}") String secret,
            @Value("${security.jwt.issuer}") String issuer) {
        // Convert secret string to SecretKey for HMAC-SHA256
        this.secretKey = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
        this.expectedIssuer = issuer;
        log.info("JwtTokenProvider initialized with issuer: {}", expectedIssuer);
    }

    /**
     * Parse and validate JWT token.
     * 
     * @param token JWT token string
     * @return Claims object containing token data
     * @throws JwtException if token is invalid, expired, or has wrong issuer
     */
    public Claims parseToken(String token) throws JwtException {
        try {
            Claims claims = Jwts.parser()
                    .verifyWith(secretKey)
                    .build()
                    .parseSignedClaims(token)
                    .getPayload();

            // Validate issuer
            String issuer = claims.getIssuer();
            if (!expectedIssuer.equals(issuer)) {
                log.warn("Token has invalid issuer: {} (expected: {})", issuer, expectedIssuer);
                throw new JwtException("Invalid token issuer");
            }

            log.debug("Token validated successfully for user: {}", claims.getSubject());
            return claims;

        } catch (ExpiredJwtException e) {
            log.warn("Token expired: {}", e.getMessage());
            throw new JwtException("Token expired", e);
        } catch (JwtException e) {
            log.warn("Token validation failed: {}", e.getMessage());
            throw e;
        }
    }

    /**
     * Extract userId from token claims.
     * 
     * @param claims Token claims
     * @return User ID
     */
    public String getUserId(Claims claims) {
        return claims.get("userId", String.class);
    }

    /**
     * Extract email from token claims.
     * 
     * @param claims Token claims
     * @return Email address
     */
    public String getEmail(Claims claims) {
        return claims.get("email", String.class);
    }

    /**
     * Extract role from token claims.
     * 
     * @param claims Token claims
     * @return User role (CUSTOMER, ADMIN, etc.)
     */
    public String getRole(Claims claims) {
        return claims.get("role", String.class);
    }

    /**
     * Check if token is valid (not expired and has correct issuer).
     * 
     * @param token JWT token string
     * @return true if token is valid, false otherwise
     */
    public boolean isValidToken(String token) {
        try {
            parseToken(token);
            return true;
        } catch (JwtException e) {
            return false;
        }
    }
}

